channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - astropy=5.3.4
  - numpy=1.26.4
  - pandas=2.2.1
  - plotly=5.19.0
  - python=3.11.8
  - root=6.30.4
  - scipy=1.12.0
  - scikit-learn=1.4.2
  - tqdm=4.66.2
  - pip:
      - kaleido==0.2.1
